# Generated by Django 3.1.1 on 2020-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200927_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
