# Generated by Django 3.1.1 on 2020-10-23 22:21

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200927_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=common.models.get_new_image_path),
        ),
    ]
