# Generated by Django 3.1.1 on 2020-09-18 14:05

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200918_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(default=shortener.models.get_brief_url, max_length=30),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='originalUrl',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
