# Generated by Django 3.1.1 on 2020-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20200918_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='clicked',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='originalUrl',
            field=models.URLField(),
        ),
    ]
