# Generated by Django 3.1.1 on 2020-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20200918_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='expirationDate',
            new_name='expiration_date',
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['creation_date'], name='shortener_s_creatio_8ebe81_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['expiration_date'], name='shortener_s_expirat_681590_idx'),
        ),
    ]
