# Generated by Django 3.1.1 on 2020-09-25 20:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20200918_1835'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shorturl',
            constraint=models.CheckConstraint(check=models.Q(creation_date__lt=django.db.models.expressions.F('expiration_date')), name='shortener_created_lt_expired'),
        ),
    ]
