# Generated by Django 3.1.1 on 2020-09-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20200925_2050'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shorturl',
            name='shortener_created_lt_expired',
        ),
    ]
