# Generated by Django 3.1.1 on 2020-10-23 22:21

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0012_auto_20200925_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(default=shortener.models.get_brief_url, max_length=30, unique=True),
        ),
    ]
