# Generated by Django 3.1.1 on 2020-09-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='catalogId',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='paste',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paste',
            name='syntax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paste.lang'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paste',
            name='url',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='pastecatalog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
