# Generated by Django 3.1.1 on 2020-09-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_auto_20200908_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='url',
            new_name='hash',
        ),
    ]
