# Generated by Django 3.1.1 on 2020-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_auto_20200918_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lang',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
