# Generated by Django 3.1.1 on 2020-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_auto_20200918_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='text',
            field=models.TextField(),
        ),
    ]
