# Generated by Django 3.1.1 on 2020-09-18 14:05

from django.db import migrations, models
import django.db.models.deletion
import paste.models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0005_auto_20200918_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paste.pastecatalog'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='hash',
            field=models.CharField(default=paste.models.get_url_hash, max_length=4096),
        ),
    ]
