# Generated by Django 3.1.1 on 2020-09-18 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paste', '0006_auto_20200918_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='expirationDate',
            new_name='expiration_date',
        ),
        migrations.AlterField(
            model_name='paste',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastecatalog',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='paste',
            index=models.Index(fields=['creation_date', 'expiration_date'], name='paste_paste_creatio_d67108_idx'),
        ),
    ]
