# Generated by Django 3.1.1 on 2020-09-18 21:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0008_auto_20200918_1834'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paste',
            constraint=models.CheckConstraint(check=models.Q(creation_date__lt=django.db.models.expressions.F('expiration_date')), name='age_gte_18'),
        ),
    ]
