# Generated by Django 3.1.1 on 2020-09-18 21:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0009_auto_20200919_0013'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paste',
            name='age_gte_18',
        ),
        migrations.AddConstraint(
            model_name='paste',
            constraint=models.CheckConstraint(check=models.Q(creation_date__lt=django.db.models.expressions.F('expiration_date')), name='created_lt_expired'),
        ),
    ]
