# Generated by Django 3.1.1 on 2020-09-25 20:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0010_auto_20200919_0028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paste',
            name='created_lt_expired',
        ),
        migrations.AddConstraint(
            model_name='paste',
            constraint=models.CheckConstraint(check=models.Q(creation_date__lt=django.db.models.expressions.F('expiration_date')), name='paste_created_lt_expired'),
        ),
    ]
