# Generated by Django 3.1.1 on 2020-09-26 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paste', '0011_auto_20200925_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastecatalog',
            unique_together={('owner', 'name')},
        ),
    ]
